services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/simple-notes
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health
      JWT_SECRET: b8d16d9d5cd0d3807f518d7ccadf9e6ae8b8022bb93b7025629edc7a3993952a14e4c2d9fd1b465775683058b23786ea5e10ed91b5fef4248a31561a3072828a
      PAGINATION_LIMIT: 1000
      RATE_LIMIT_CAPACITY: 30
      RATE_LIMIT_MINUTES: 1
      RATE_LIMIT_BURST_CAPACITY: 5
      RATE_LIMIT_BURST_SECONDS: 1
      JWT_ACCESS_TOKEN_EXPIRATION: 1800000
      JWT_REFRESH_TOKEN_EXPIRATION: 259200000

    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: simple-notes
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:
