spring:
  sql.init.mode: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/secure-notes
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    defer-datasource-initialization: true

secure-notes:
  pagination.limit: 1000
  rate-limit:
    capacity: 30
    minutes: 1
    burst:
      capacity: 5
      seconds: 1
  security:
    jwt:
      secret: b8d16d9d5cd0d3807f518d7ccadf9e6ae8b8022bb93b7025629edc7a3993952a14e4c2d9fd1b465775683058b23786ea5e10ed91b5fef4248a31561a3072828a
      accessTokenExpiration: 1_800_000
      refreshTokenExpiration: 259_200_000
